import { ghRequest } from "@/lib/github";
export async function probe(path:string):Promise<{ok:boolean;status:number;message:string}>{const res=await ghRequest(path);return{ok:res.ok,status:res.status,message:res.ok?"Available":`Unavailable or missing scope (${res.status})`}}
export async function getBranchProtection(owner:string,repo:string,branch:string){return probe(`/repos/${owner}/${repo}/branches/${encodeURIComponent(branch)}/protection`)}
export async function getDependabot(owner:string,repo:string){return probe(`/repos/${owner}/${repo}/dependabot/alerts?per_page=1`)}
export async function getCodeScanning(owner:string,repo:string){return probe(`/repos/${owner}/${repo}/code-scanning/alerts?per_page=1`)}
export async function getSecretScanning(owner:string,repo:string){return probe(`/repos/${owner}/${repo}/secret-scanning/alerts?per_page=1`)}
export function codeownersTemplate(owner:string):string{return [`# CODEOWNERS generated by GitHub Browser Control Panel`,`* @${owner}`,`/src/ @${owner}`,``].join("\n")}
