"use client";
import { useEffect, useState } from "react";
import { useActiveRepo } from "@/lib/store";
import { classifyPr } from "./classify";
import { closePull, listPulls, mergePull, type PullRequestSummary } from "./api";
export function PullsPanel({ open, onClose }: { open: boolean; onClose: () => void }) {
 const repo=useActiveRepo(); const meta=repo?.meta; const [items,setItems]=useState<PullRequestSummary[]>([]); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false);
 useEffect(()=>{ if(!open||!meta) return; setLoading(true); setError(null); listPulls(meta.owner,meta.repo).then(setItems).catch(e=>setError(e instanceof Error?e.message:"Failed to load PRs")).finally(()=>setLoading(false)); },[open,meta]);
 if(!open) return null; return <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/50 p-8" onClick={onClose}><div className="max-h-[80vh] w-full max-w-3xl overflow-auto rounded-xl border border-neutral-800 bg-neutral-950 p-4 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold text-neutral-100">Pull Requests</h2><button onClick={onClose} className="text-neutral-400 hover:text-white">Close</button></div>{loading&&<p className="text-neutral-500">Loading…</p>}{error&&<p className="rounded border border-red-900 bg-red-950/40 p-2 text-red-300">{error}</p>}<div className="space-y-2">{items.map(pr=><div key={pr.number} className="rounded-lg border border-neutral-800 bg-neutral-900 p-3"><div className="flex gap-2"><span className="text-blue-300">#{pr.number}</span><a href={pr.htmlUrl} target="_blank" rel="noreferrer" className="flex-1 text-neutral-100 hover:underline">{pr.title}</a><span className="rounded bg-neutral-800 px-2 py-0.5 text-xs text-neutral-300">{classifyPr(pr)}</span></div><div className="mt-1 text-xs text-neutral-500">{pr.user} · {pr.changedFiles} files · +{pr.additions}/-{pr.deletions}</div><div className="mt-2 flex gap-2"><button onClick={()=>meta&&mergePull(meta.owner,meta.repo,pr.number).then(()=>setItems(v=>v.filter(x=>x.number!==pr.number))).catch(e=>setError(String(e)))} className="rounded bg-green-700 px-2 py-1 text-xs text-white">Merge</button><button onClick={()=>meta&&closePull(meta.owner,meta.repo,pr.number).then(()=>setItems(v=>v.filter(x=>x.number!==pr.number))).catch(e=>setError(String(e)))} className="rounded bg-neutral-800 px-2 py-1 text-xs text-neutral-200">Close</button></div></div>)}</div></div></div>;
}
