"use client";
import { useEffect, useState } from "react";
import { useActiveRepo } from "@/lib/store";
import { classifyPr } from "./classify";
import { closePull, listPulls, mergePull, type PullRequestSummary } from "./api";
export function PullsPanel({ open, onClose }: { open: boolean; onClose: () => void }) {
 const repo=useActiveRepo(); const meta=repo?.meta; const [items,setItems]=useState<PullRequestSummary[]>([]); const [error,setError]=useState<string|null>(null); const [loading,setLoading]=useState(false);
 useEffect(()=>{ if(!open||!meta) return; setLoading(true); setError(null); listPulls(meta.owner,meta.repo).then(setItems).catch(e=>setError(e instanceof Error?e.message:"Failed to load PRs")).finally(()=>setLoading(false)); },[open,meta]);
 if(!open) return null; return <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/25 p-8" onClick={onClose}><div className="max-h-[80vh] w-full max-w-3xl overflow-auto rounded-xl border border-[var(--dh-window-border)] bg-[color-mix(in_srgb,var(--dh-surface)_82%,transparent)] p-4 shadow-2xl backdrop-blur-2xl backdrop-saturate-150" onClick={e=>e.stopPropagation()}><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold text-[var(--dh-text)]">Pull Requests</h2><button onClick={onClose} className="text-[var(--dh-text-secondary)] hover:text-[var(--dh-text)]">Close</button></div>{loading&&<p className="text-[var(--dh-text-secondary)]">Loading…</p>}{error&&<p className="rounded border border-red-200 dark:border-red-900 bg-red-50 dark:bg-red-950/40 p-2 text-red-600 dark:text-red-300">{error}</p>}<div className="space-y-2">{items.map(pr=><div key={pr.number} className="rounded-lg border border-[var(--dh-window-border)] bg-[var(--dh-surface-raised)] p-3"><div className="flex gap-2"><span className="text-blue-700 dark:text-blue-300">#{pr.number}</span><a href={pr.htmlUrl} target="_blank" rel="noreferrer" className="flex-1 text-[var(--dh-text)] hover:underline">{pr.title}</a><span className="rounded bg-[var(--dh-surface-hover)] px-2 py-0.5 text-xs text-[var(--dh-text-secondary)]">{classifyPr(pr)}</span></div><div className="mt-1 text-xs text-[var(--dh-text-secondary)]">{pr.user} · {pr.changedFiles} files · +{pr.additions}/-{pr.deletions}</div><div className="mt-2 flex gap-2"><button onClick={()=>meta&&mergePull(meta.owner,meta.repo,pr.number).then(()=>setItems(v=>v.filter(x=>x.number!==pr.number))).catch(e=>setError(String(e)))} className="rounded bg-green-700 px-2 py-1 text-xs text-white">Merge</button><button onClick={()=>meta&&closePull(meta.owner,meta.repo,pr.number).then(()=>setItems(v=>v.filter(x=>x.number!==pr.number))).catch(e=>setError(String(e)))} className="rounded bg-[var(--dh-surface-hover)] px-2 py-1 text-xs text-[var(--dh-text)]">Close</button></div></div>)}</div></div></div>;
}
