/**
 * Central Fluent System Icons re-export for DRAGHUB. Every name here has
 * been checked against the installed `@fluentui/react-icons` package and
 * its TypeScript definitions — nothing here is guessed. This replaces the
 * hand-drawn SVGs in the old `src/components/icons.tsx`.
 *
 * Convention: Regular is the default for a static/inactive state; the
 * matching Filled variant represents an active, selected or emphasized
 * state (per-usage, not a blanket swap).
 */
export {
  ChevronRightRegular,
  ChevronDownRegular,
  ChevronUpRegular,
  FolderRegular,
  FolderFilled,
  FolderOpenRegular,
  FolderOpenFilled,
  FolderAddRegular,
  FolderZipRegular,
  DocumentRegular,
  DocumentFilled,
  DocumentTextRegular,
  DocumentAddRegular,
  ImageRegular,
  ImageFilled,
  GlobeRegular,
  MusicNote2Regular,
  MusicNote2Filled,
  MarkdownRegular,
  CodeRegular,
  CodeFilled,
  OpenRegular,
  CopyRegular,
  ArrowDownloadRegular,
  ArrowUploadRegular,
  ArrowClockwiseRegular,
  ArrowSyncRegular,
  ArrowSyncFilled,
  ArrowUndoRegular,
  SearchRegular,
  SearchFilled,
  DismissRegular,
  DismissFilled,
  DismissCircleRegular,
  AddRegular,
  StarRegular,
  StarFilled,
  BranchForkRegular,
  BranchForkFilled,
  BranchRequestRegular,
  HomeRegular,
  LineHorizontal3Regular,
  ReOrderDotsVerticalRegular,
  ClockRegular,
  DeleteRegular,
  DeleteFilled,
  BinRecycleRegular,
  BinRecycleFilled,
  EditRegular,
  EditFilled,
  SaveRegular,
  SettingsRegular,
  SettingsFilled,
  AppsRegular,
  AppsFilled,
  AppFolderRegular,
  AppFolderFilled,
  BugRegular,
  BugFilled,
  PlayCircleRegular,
  PlayCircleFilled,
  FlashRegular,
  FlashFilled,
  TableRegular,
  TableFilled,
  TagRegular,
  TagFilled,
  ShieldCheckmarkRegular,
  ShieldCheckmarkFilled,
  GridRegular,
  GridFilled,
  ListRegular,
  ListFilled,
  MaximizeRegular,
  ArrowMinimizeRegular,
  SubtractRegular,
  WarningRegular,
  WarningFilled,
  ErrorCircleRegular,
  ErrorCircleFilled,
  InfoRegular,
  CheckmarkCircleRegular,
  CheckmarkCircleFilled,
  PlugConnectedRegular,
  PlugConnectedFilled,
  DesktopRegular,
  MoreHorizontalRegular,
  ChevronUpDownRegular,
  RecordRegular,
  SpinnerIosRegular,
} from "@fluentui/react-icons";

export type { FluentIcon } from "@fluentui/react-icons";
