import { ghRequest } from "@/lib/github";

export type ScopedResult<T> =
  | { status: "ok"; items: T[] }
  | { status: "forbidden"; message: string }
  | { status: "unavailable"; message: string }
  | { status: "error"; message: string };

export type Collaborator = { login: string; permission: string; htmlUrl: string };
export type Team = { slug: string; name: string; permission: string };

export async function fetchCollaborators(owner: string, repo: string): Promise<ScopedResult<Collaborator>> {
  const res = await ghRequest(`/repos/${owner}/${repo}/collaborators?per_page=100`);
  if (res.status === 403) {
    return { status: "forbidden", message: 'Token is missing "Administration: read" (or repo scope).' };
  }
  if (res.status === 404) return { status: "unavailable", message: "Not available for this repository." };
  if (!res.ok) return { status: "error", message: `Request failed (${res.status}).` };
  const data = await res.json<
    Array<{ login: string; permissions?: Record<string, boolean>; html_url: string }>
  >();
  return {
    status: "ok",
    items: data.map((c) => ({
      login: c.login,
      permission: c.permissions?.admin ? "admin" : c.permissions?.push ? "write" : "read",
      htmlUrl: c.html_url,
    })),
  };
}

export async function fetchTeams(owner: string, repo: string): Promise<ScopedResult<Team>> {
  const res = await ghRequest(`/repos/${owner}/${repo}/teams?per_page=100`);
  if (res.status === 403) return { status: "forbidden", message: 'Token is missing "admin:org" (or this is not an org repo).' };
  if (res.status === 404) return { status: "unavailable", message: "No teams — this repository isn't owned by an organization." };
  if (!res.ok) return { status: "error", message: `Request failed (${res.status}).` };
  const data = await res.json<Array<{ slug: string; name: string; permission: string }>>();
  return { status: "ok", items: data.map((t) => ({ slug: t.slug, name: t.name, permission: t.permission })) };
}

export function generateCodeowners(owners: string[]): string {
  const lines = [
    "# Generated by GitHub Browser's Control Panel — Access applet.",
    "# Edit paths/owners as needed; this is a starting point, not a full policy.",
    "",
    `* ${owners.map((o) => `@${o}`).join(" ")}`.trimEnd(),
    "",
  ];
  return lines.join("\n");
}
